### ISSUE TITLE
Missing commit at zeronvs-diffusion

### ISSUE THREAD

**Issue by eneserciyes** [s-tian/ZeroNVS#1]
Hi,

The zeronvs-diffusion commit here is either inaccessible or squashed. Could you point me to the correct commit in the repo?

**Comment by s-tian** [comment]
Sorry about this, I've corrected the commit in the repo to [this one](https://github.com/kylesargent/zeronvs_diffusion/tree/f82b71a29ad7497b8d4b6bbbcd8aea44ed5c43a9). Please let me know if you have any further issues!
